### ISSUE TITLE
Meta and Datatables

### ISSUE THREAD

**Issue by rcnlee** [milktrader/Quandl.jl#107]
Can this package be used to access the meta and datatables 
API? For example, to get to the Wiki EOD Stock Prices?
https://www.quandl.com/data/WIKI-Wiki-EOD-Stock-Prices/documentation/documentation?modal=null
Thanks!

**Comment by milktrader** [comment]
Quandl.jl (documentation)[http://quandljl.readthedocs.io/en/latest/]
