### ISSUE TITLE
julia: symbol lookup error: /usr/lib/x86_64-linux-gnu/libhogweed.so.2: undefined symbol: __gmpn_cnd_add_n

### ISSUE THREAD

**Issue by alpo** [milktrader/Quandl.jl#80]
Calling `quandl("GOOG/NASDAQ_QQQ")` gives Julia crash with message

    julia: symbol lookup error: /usr/lib/x86_64-linux-gnu/libhogweed.so.2: undefined symbol: __gmpn_cnd_add_n

Julia 0.3.10, 0.3.11
Debian 8.1 (Jessie)
nothing non-standard

**Comment by milktrader** [comment]
This is odd but looks like it's an upstream error. I'll try to replicate it by installing 3.10.

**Comment by milktrader** [comment]
https://github.com/milktrader/Quandl.jl/issues/82

**Comment by milktrader** [comment]
I've tracked down some bugs with the Requests package changing their semantics so I'm going to close this issue for now. I cannot duplicate it. Reopen this if you still have issues after running a `Pkg.update()`. I've tagged bug fixes with version 0.4.3

**Comment by alpo** [comment]
Still not fixed after Quandl update to 0.4.3. But it is definitely upstream error, GnuTLS, HTTPClient, Requests and LibCURL doesn't work with HTTPS too.

**Comment by git-lc** [comment]
rm /usr/local/lib/libgmp.so*
https://unix.stackexchange.com/a/279649
This fixes it for me.
