### ISSUE TITLE
no method matching split

### ISSUE THREAD

**Issue by DataWookie** [milktrader/Quandl.jl#81]
Hi,

I'm running Julia 0.3.10 and Quandl 0.4.2.

    julia> quandl("GOOG/NASDAQ_QQQ")
        ERROR: `split` has no method matching split(::Array{Uint8,1}, ::ASCIIString)
         in timearray at /home/colliera/.julia/v0.3/Quandl/src/timearray.jl:6
         in quandlget at /home/colliera/.julia/v0.3/Quandl/src/api.jl:27

Strange thing is that this was working fine a week or so ago. Not sure what has changed. The above error was generated in a "fresh" Julia session in which I simply loaded the Quandl package and then tried to grab the NASDAQ data.

Thanks,
Andrew.

**Comment by DataWookie** [comment]
I tried this on juliabox.org too. This time with the 0.3.11 kernel of Julia. Same error, so this does not seem to be a problem local to my install.

![image](https://cloud.githubusercontent.com/assets/6134409/9699608/c601bb12-53e9-11e5-840c-5f1b0fff440b.png)

**Comment by milktrader** [comment]
I'm installing 0.3.11 to try and track down this and should get to it soon. Thanks for the issue.

**Comment by DataWookie** [comment]
Thank you, much appreciated.

**Comment by milktrader** [comment]
Well I'm getting a separate error ...

````
julia> using Quandl
ERROR: Compat not found
 in require at loading.jl:47
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128 in reload_path at loading.jl:152 in _require at loading.jl:67 in require at loading.jl:54 in include at ./boot.jl:245 in include_from_node1 at ./loading.jl:128 in reload_path at loading.jl:152 in _require at loading.jl:67 in require at loading.jl:51while loading /Users/Administrator/.julia/v0.3/TimeSeries/src/TimeSeries.jl, in expression starting on line 15while loading /Users/Administrator/.julia/v0.3/Quandl/src/Quandl.jl, in expression starting on line 2                                                                                 
````

**Comment by milktrader** [comment]
Trying to install `Compat` gives me this:

````julia
julia> Pkg.add("Compat")ERROR: REPL can't be installed because it has no versions that support 0.3.11 of julia. You may need to update METADATA by running `Pkg.update()`
 in wait at ./task.jl:284
 in wait at ./task.jl:194
 in wait at task.jl:48
 in sync_end at ./task.jl:311
 in add at pkg/entry.jl:319
 in add at pkg/entry.jl:71
 in anonymous at pkg/dir.jl:28
 in cd at ./file.jl:20
 in __cd#229__ at ./pkg/dir.jl:28
 in add at pkg.jl:20
````
And after running a `Pkg.update()` I get this recursive suggestion ....

````julia
INFO: Computing changes...
ERROR: REPL can't be installed because it has no versions that support 0.3.11 of julia. You may need to update METADATA by running `Pkg.update()`
 in error at error.jl:22
 in resolve at ./pkg/entry.jl:378
 in update at ./pkg/entry.jl:280
 in anonymous at pkg/dir.jl:28
 in cd at ./file.jl:20
 in __cd#229__ at ./pkg/dir.jl:28
 in update at ./pkg.jl:41
````

**Comment by milktrader** [comment]
Well now getting past those warnings, I find a point of failure here:
````julia
julia> response = get("https://www.quandl.com/api/v1/datasets/$id.csv", query = query_args)
ERROR: stream is closed or unusable
 in check_open at stream.jl:294
 in write at stream.jl:730
 in close at /Users/Administrator/.julia/v0.3/GnuTLS/src/GnuTLS.jl:96
 in readtobuf at /Users/Administrator/.julia/v0.3/GnuTLS/src/GnuTLS.jl:378
 in readavailable at /Users/Administrator/.julia/v0.3/GnuTLS/src/GnuTLS.jl:401
 in process_response at /Users/Administrator/.julia/v0.3/Requests/src/Requests.jl:228
 in do_request at /Users/Administrator/.julia/v0.3/Requests/src/Requests.jl:563
 in get at /Users/Administrator/.julia/v0.3/Requests/src/Requests.jl:577
 in get at /Users/Administrator/.julia/v0.3/Requests/src/Requests.jl:576
````

**Comment by milktrader** [comment]
Hmmm, seems like we have a bigger issue here ... From the Quandl documentation

>Legacy users may want to read the API v1 docs. Note that v1 of the Quandl API is no longer actively maintained, and is on the path to eventual deprecation. We encourage all users to switch to the date-based API v3.

**Comment by milktrader** [comment]
https://github.com/milktrader/Quandl.jl/issues/82

**Comment by milktrader** [comment]
https://github.com/JuliaWeb/Requests.jl/issues/66

**Comment by DataWookie** [comment]
Thanks for all the work you've put into this. I look forward to milktrader/Quandl.jl on the new API. Please let me know if I can contribute in any way.

**Comment by milktrader** [comment]
We have two separate assaults on this package. The lesser one is the Quandl API, the bigger one is the fact that Requests.jl has recently changed (10 days ago or so) what `.data` on a Requests object means. 

The trick short term will be to put a floor and ceiling on the version of Requests where the change happened. I'll try to hunt this down but the general idea is to include the following in the `REQUIRE` file:

```
julia 0.3
Dates
TimeSeries
DataFrames
Requests 0.2.4 0.3
JSON
````

**Comment by milktrader** [comment]
https://github.com/JuliaWeb/Requests.jl/issues/72

**Comment by milktrader** [comment]
Once I removed `REPL` from my v0.3 package directory, `Pkg.update()` has been able to do its thing. IN any case, this should remove one roadblock to debugging this issue ...

**Comment by milktrader** [comment]
Ok, here is the issue now that I've got my 0.3 workspace issues sorted out. 

````julia
julia> response = Requests.get("https://www.quandl.com/api/v3/datasets/WIKI/AAPL.csv");

julia> response.data
1129573-element Array{Uint8,1}:
 0x44
 0x61
 0x74
 0x65
 0x2c
 0x4f
 0x70
 0x65
    ⋮
 0x38
 0x34
 0x30
 0x30
 0x2e
 0x30
 0x0a
````

**Comment by milktrader** [comment]
Alright, change of strategy here to solve this. Instead of putting a ceiling on Requests, I'm just going to change `response.data` to `Requests.text(response)`. Simple enough.

**Comment by milktrader** [comment]
Hmm, now that JLD has matured, it may be time to revisit the testing suite which depends on it.

**Comment by milktrader** [comment]
Version 0.4.3 takes care of this and should be ready once it gets merged into METADATA (within the hour).

**Comment by milktrader** [comment]
Okay, you should be good to go. Let me know if you find anything else.

Short term goals are to start using Quandl's api v3 and getting JLD objects to work for meaningful tests.

**Comment by DataWookie** [comment]
Fantastic. :-) Thank you very much for sorting that out so promptly!
