### ISSUE TITLE
Add const file for commonly used datasets

### ISSUE THREAD

**Issue by milktrader** [milktrader/Quandl.jl#83]
For example, using version 3 of the Quandl api:

````julia
const AAPL = "https://www.quandl.com/api/v3/datasets/WIKI/AAPL.csv"
````
So a call to get Apple stock prices can be done thusly:

````julia
julia> quandl(AAPL)
````

**Comment by prcastro** [comment]
Today, wouldn't this call be:

```julia
julia> quandl("AAPL")
```

**Comment by milktrader** [comment]
Do you mean that's part of v3 api?

**Comment by prcastro** [comment]
No, I meant I didn't know what the call was. Know I know the call is something like `quandl("WIKI/AAPL")`. I was just trying to understand what would we achieve by defining these consts, and now I do.

**Comment by milktrader** [comment]
Yeah, the call would be `quandl(AAPL)`, but maybe this is better suited for a separate package, something like `QuandlConst`
