### ISSUE TITLE
Deprecated Base.Uint8 and Base.Nothing

### ISSUE THREAD

**Issue by cndesantana** [milktrader/Quandl.jl#88]
Hi,

Running the example in the docs, I found out some deprecated messages:

julia> quandl("GOOG/NASDAQ_QQQ")
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
WARNING: Base.Nothing is deprecated, use Void instead.
WARNING: Base.Nothing is deprecated, use Void instead.
WARNING: Base.Nothing is deprecated, use Void instead.
WARNING: Base.Nothing is deprecated, use Void instead.
in timearray at /home/cdesantana/.julia/v0.4/Quandl/src/timearray.jl:40
WARNING: Base.Nothing is deprecated, use Void instead.
in timearray at /home/cdesantana/.julia/v0.4/Quandl/src/timearray.jl:40

Is it possible to eliminate these warnings? Do they have any effect in the performance of Quandl?

Thanks!

**Comment by milktrader** [comment]
They don't have any performance hit other than the initial printing of grievances. What version of Julia are you running?

You can checkout your own branch, make changes, commit them and then push the branch to your fork and then github will fashion a PR, which I'll be happy to merge.

**Comment by milktrader** [comment]
Oh, duh. You're on 0.4. Which minor release?

**Comment by milktrader** [comment]
I get the following deprecation warnings on 0.4.0
````
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /Users/Administrator/.julia/v0.4/Quandl/src/api.jl:1
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /Users/Administrator/.julia/v0.4/Quandl/src/api.jl:1
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /Users/Administrator/.julia/v0.4/Quandl/src/api.jl:1
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /Users/Administrator/.julia/v0.4/Quandl/src/api.jl:120
````

**Comment by cndesantana** [comment]
Hi,

Thanks for your response. I am running Julia Version 0.4.0-rc3 (2015-09-27 20:34 UTC) in Ubuntu 14.04.

I will do the changes in my own branch as you suggested. Let's keep in touch about it!

Best,

Charles
________________________________

**Comment by milktrader** [comment]
No problem, let me know if you run into any problems with the PR. I'll end up doing this in a week or so if you don't get to it.

**Comment by cndesantana** [comment]
Hi,

Thanks for this! 

I did the changes in my machine and I created a branch (warningfixes). So I tried to commit the changes to this new branch but I receive the following message: 

cdesantana@charles:~/.julia/v0.4/Quandl$ git push origin warningsfixes 
Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Does it mean that I need to send my public key to Quandl repository? Sorry, it is the very first time I contribute to a open source project in this way :)

Thanks!

**Comment by cndesantana** [comment]
Hi again,

I updated my public key and sent it again to Github. So now the error message is a bit different:

cdesantana@charles:~/.julia/v0.4/Quandl$ git push origin warningsfixes 
Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
ERROR: Permission to milktrader/Quandl.jl.git denied to cndesantana.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Thanks!

**Comment by milktrader** [comment]
You need to `git remote add [whatever name you want not origin though] [your github fork address]` and then `git push --set-upstream [whatever you named it above] warningfixes`

**Comment by cndesantana** [comment]
Many thanks!! I hope it has worked now!

Best,

Charles

________________________________

**Comment by prcastro** [comment]
I think this can be closed now
