### ISSUE TITLE
quandlsearch ERROR

### ISSUE THREAD

**Issue by cndesantana** [milktrader/Quandl.jl#89]
Hi,

Trying to run one of the examples in the documentation I got the following error message: 

julia> using Quandl

        julia> df = quandlsearch("GDP USA", results=30)
        Returning 30 results of 412331 from page 1
        ERROR: ArgumentError: number of columns of each array must match (got (1,2,2))
         in typed_vcat at abstractarray.jl:810
         in vcat at abstractarray.jl:802
         in hvcat at abstractarray.jl:1021
         in quandlsearch at /home/cdesantana/.julia/v0.4/Quandl/src/api.jl:64

Is it an error in my installation? Any tip?

I am using Julia Version 0.4.2-pre+15 (2015-11-20 12:12 UTC) in Ubuntu 14.04

Thanks!

Charles

**Comment by milktrader** [comment]
It's in the DataFrames construction. I'm getting the same error.
