### ISSUE TITLE
ERROR: 429: Error executing the request.

### ISSUE THREAD

**Issue by cndesantana** [milktrader/Quandl.jl#99]
Hi,

I just updated Quandl.jl (I removed my former directory ~/.julia/v0.4/Quandl and installed Quandl.jl using Pkg.clone("...") from my Julia terminal). Now I can not run my former codes, neither the examples from the documentation.

        julia> using Quandl
        INFO: Recompiling stale cache file /home/cdesantana/.julia/lib/v0.4/Quandl.ji for module Quandl.

running the documentation example with format "DataFrame" I got the following error:

        julia> quandl("GOOG/NASDAQ_QQQ", format="DataFrame")
        ERROR: 429: Error executing the request.
         in error at ./error.jl:21
         in quandlget at /home/cdesantana/.julia/v0.4/Quandl/src/api.jl:22

and with format TimeArray I got the following one:

        julia> quandl("GOOG/NASDAQ_QQQ")
        ERROR: 429: Error executing the request.
         in error at ./error.jl:21
         in quandlget at /home/cdesantana/.julia/v0.4/Quandl/src/api.jl:22

and running my own script I got the following error:

        cdesantana@charles:~/.julia/v0.4/RobHood/test$ julia runtests.jl 
        ERROR: LoadError: 429: Error executing the request.
         in error at ./error.jl:21
         in quandlget at /home/cdesantana/.julia/v0.4/Quandl/src/api.jl:22
        ...

Is it a problem with the API, with my installation, or is it a problem with Quandl server?

Thanks for your attention!

Best,

**Comment by cndesantana** [comment]
Hi,

Apparently the reason of that error was that I needed to give my auth_token again. I just run set_auth_token("mytoken") and I was able to run the examples in the documentation. 

Sorry for opening an issue for such a silly "problem". 

Thanks!

**Comment by prcastro** [comment]
It's nice to have this somewhere here on the issues log, since more than one user could run into this problem. Just remember to close the bug! =)

**Comment by milktrader** [comment]
No, thank you for filing the issue! And better yet solving it yourself !
